import { Inter } from "next/font/google";
import "./globals.css";
import ResponsiveNav from "@/components/Home/ResponsiveNav";
import Footer from "@/components/Home/Footer";

const font = Inter({
  weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'],
  subsets: ['latin']
})
// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata = {
  title: "Logoipsum",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={` ${font.className} antialiased`}
      >
        <ResponsiveNav/>
        {children}
       <Footer/>
      </body>
    </html>
  );
}
